spring.application.name=cbc_vcms_internal
spring.data.mongodb.uri=mongodb+srv://stanley_e:L8YegQ9YtgWGaWbQ@cluster0.lhvge.mongodb.net/vcms?retryWrites=true&w=majority
spring.data.mongodb.database=vcms